# Generated by Django 3.0.4 on 2020-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
