# Generated by Django 3.0.4 on 2020-05-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
