# Generated by Django 3.0.4 on 2020-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
